-- @description PonSE
-- @version 1.0
-- @author yukinori-okd
-- @provides
--   [main] PonSE/y-okd_PonSE1.lua
--   [main] PonSE/y-okd_PonSE2.lua
--   [main] PonSE/y-okd_PonSE3.lua
--   [main] PonSE/y-okd_PonSE4.lua
--   [main] PonSE/y-okd_PonSE5.lua
--   [main] PonSE/y-okd_PonSE6.lua
--   [main] PonSE/y-okd_PonSE7.lua
--   [main] PonSE/y-okd_PonSE8.lua
--   [main] PonSE/y-okd_PonSE9.lua
--   [main] PonSE/y-okd_PonSE10.lua
--   [main] PonSE/y-okd_PonSE11.lua
--   [main] PonSE/y-okd_PonSE12.lua
--   [main] PonSE/y-okd_PonSEManager.lua
-- @about
--   SEのポン出し用スクリプト群（マネージャーを起動した状態で使用する必要があります）
--
--   PonSEManager.luaはSEトラックの子トラックを取得して一覧として表示し、そのUIからSEを再生することも可能です。
--
--   PonSE<Num>.luaはPonSEManagerが起動している際に実行すると、指定番号のSEを鳴らすことができます。MIDI信号を割り当て、MIDIコントローラーで操作するため用です。
